name: Python Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: python -m pip install -U pip uv

      - name: Install dependencies
        run: uv sync --frozen --group dev

      - name: Run pytest
        run: >
          uv run pytest --cov=teltasync --cov-report=term-missing
          --cov-report=xml --cov-fail-under=90
