# Publish to PyPI from Forgejo Actions.
# Triggers on a published release

name: Upload Python Package

on:
  release:
    types: [published, edited]

permissions:
  contents: read

jobs:
  pypi-publish:
    runs-on: codeberg-small

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build distributions
        run: |
          python -m pip install -U pip build
          python -m build

      - name: Publish to PyPI (API token)
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install -U twine
          twine upload dist/*